version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lacrei_db
    restart: always
    environment:
      POSTGRES_DB: lacrei
      POSTGRES_USER: lacrei
      POSTGRES_PASSWORD: lacrei
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: lacrei_api
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_NAME: lacrei
      DB_USER: lacrei
      DB_PASSWORD: lacrei
      DB_PORT: 5432

volumes:
  postgres_data:
